-- Customers table - Customer accounts
CREATE TABLE IF NOT EXISTS customers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    account_number VARCHAR(20) UNIQUE NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100),
    phone VARCHAR(20) NOT NULL,
    id_number VARCHAR(20),
    property_type ENUM('residential', 'commercial', 'industrial', 'institutional') NOT NULL DEFAULT 'residential',
    property_name VARCHAR(100),
    address TEXT NOT NULL,
    zone_id INT,
    route_id INT,
    connection_status ENUM('active', 'inactive', 'disconnected', 'suspended') DEFAULT 'active',
    connection_date DATE,
    balance DECIMAL(12, 2) DEFAULT 0.00,
    deposit_amount DECIMAL(12, 2) DEFAULT 0.00,
    is_active BOOLEAN DEFAULT TRUE,
    portal_password_hash VARCHAR(255),
    portal_enabled BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by INT,
    FOREIGN KEY (zone_id) REFERENCES zones(id) ON DELETE SET NULL,
    FOREIGN KEY (route_id) REFERENCES routes(id) ON DELETE SET NULL,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_account (account_number),
    INDEX idx_phone (phone),
    INDEX idx_zone (zone_id),
    INDEX idx_route (route_id),
    INDEX idx_status (connection_status),
    INDEX idx_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
