-- Meter readings table - Recorded readings
CREATE TABLE IF NOT EXISTS meter_readings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    meter_id INT NOT NULL,
    customer_id INT NOT NULL,
    reading_date DATE NOT NULL,
    current_reading DECIMAL(10, 2) NOT NULL,
    previous_reading DECIMAL(10, 2) NOT NULL,
    consumption DECIMAL(10, 2) NOT NULL,
    reader_id INT,
    route_id INT,
    photo_url VARCHAR(255),
    notes TEXT,
    anomaly_flags JSON,
    is_estimated BOOLEAN DEFAULT FALSE,
    is_billed BOOLEAN DEFAULT FALSE,
    billing_period VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (meter_id) REFERENCES meters(id) ON DELETE CASCADE,
    FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE,
    FOREIGN KEY (reader_id) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (route_id) REFERENCES routes(id) ON DELETE SET NULL,
    INDEX idx_meter (meter_id),
    INDEX idx_customer (customer_id),
    INDEX idx_date (reading_date),
    INDEX idx_billed (is_billed),
    INDEX idx_period (billing_period)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
